# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  ...
}:

{
  boot.initrd.availableKernelModules = [
    "ehci_pci"
    "ahci"
    "xhci_pci"
    "nvme"
    "usbhid"
    "sr_mod"
  ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/6a0da8af-c9e4-41aa-be3b-c5877e0d5a28";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/A4B2-A299";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/c023671f-ca3e-4216-b184-63ee0f9d51cf"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
