#!/usr/bin/env bash

export EDITOR=nvim
export GREP_COLOR='1;36'
export LSCOLORS='ExGxbEaECxxEhEhBaDaCaD'
export PAGER='less'

source <(fzf --bash)

# History
HISTFILE="$HOME/.bash_history"
HISTSIZE=10000000
SAVEHIST=10000000

# Support colors in less
export LESS_TERMCAP_mb=$(tput bold; tput setaf 1)
export LESS_TERMCAP_md=$(tput bold; tput setaf 1)
export LESS_TERMCAP_me=$(tput sgr0)
export LESS_TERMCAP_se=$(tput sgr0)
export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4)
export LESS_TERMCAP_ue=$(tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 2)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)

alias lg=lazygit

# Enable color support of ls
if ls --color=auto &>/dev/null; then
        alias ls='ls -p --color=auto'
else
        alias ls='ls -p -G'
fi

# print a colorized diff
colordiff() {
        local red=$(tput setaf 1 2>/dev/null)
        local green=$(tput setaf 2 2>/dev/null)
        local cyan=$(tput setaf 6 2>/dev/null)
        local reset=$(tput sgr0 2>/dev/null)

        diff -u "$@" | awk "
        /^\-/ {
                printf(\"%s\", \"$red\");
        }
        /^\+/ {
                printf(\"%s\", \"$green\");
        }
        /^@/ {
                printf(\"%s\", \"$cyan\");
        }

        {
                print \$0 \"$reset\";
        }"

        return "${PIPESTATUS[0]}"
}

# Print all 256 colors
colors() {
        local i
        for i in {0..255}; do
                printf "\x1b[38;5;${i}mcolor %d\n" "$i"
        done
        tput sgr0
}

# print a rainbow if truecolor is available to the terminal
truecolor-rainbow() {
        local i r g b
        for ((i = 0; i < 77; i++)); do
                r=$((255 - (i * 255 / 76)))
                g=$((i * 510 / 76))
                b=$((i * 255 / 76))
                ((g > 255)) && g=$((510 - g))
                printf '\033[48;2;%d;%d;%dm ' "$r" "$g" "$b"
        done
        tput sgr0
        echo
}


# Change the prompt colors to a theme, themes are 0-29
set_prompt_colors() {
        local h=${1:-0}
        local color=
        local i=0
        local j=0
        for i in {22..231}; do
                ((i % 30 == h)) || continue

                color=${COLOR256[$i]}
                # cache the tput colors
                if [[ -z $color ]]; then
                        COLOR256[$i]=$(tput setaf "$i")
                        color=${COLOR256[$i]}
                fi
                PROMPT_COLORS[$j]=$color
                ((j++))
        done
}

# Define reset color
RESET_COLOR=$(tput sgr0)

# Construct the prompt
# [(exit code)] <user> - <hostname> <uname> <cwd> [git branch] <$|#>

# exit code of last process
PS1='$(ret=$?;(($ret!=0)) && echo "\[${COLOR256[0]}\]($ret) \[\033[0m\]")'

# username (red for root)
PS1+='\[${PROMPT_COLORS[0]}\]$(((UID==0)) && echo "\[${COLOR256[0]}\]")\u\[\033[0m\]@'

# zonename (global zone warning)
PS1+='\[${COLOR256[0]}\]'"$(zonename 2>/dev/null | grep -q '^global$' && echo 'GZ:')"'\[\033[0m\]'

# hostname
PS1+='\[${PROMPT_COLORS[3]}\]\H '

# PID
# PS1+='\[${PROMPT_COLORS[4]}\](PID:$$) \[\033[0m\]'

# uname
# PS1+='\[${PROMPT_COLORS[2]}\]'"$(uname | tr '[:upper:]' '[:lower:]')"' '

# cwd
PS1+='\[${PROMPT_COLORS[5]}\]\w '

# optional git branch
PS1+='$(branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null); [[ -n $branch ]] && echo "\[${PROMPT_COLORS[2]}\](\[${PROMPT_COLORS[3]}\]git:$branch\[${PROMPT_COLORS[2]}\]) ")'

# prompt character
PS1+='\[${PROMPT_COLORS[0]}\]\$\[\033[0m\] '

# set the theme
set_prompt_colors 24

# Prompt command
_prompt_command() {
        local user=$USER
        local host=${HOSTNAME%%.*}
        local pwd=${PWD/#$HOME/\~}
        local ssh=
        [[ -n $SSH_CLIENT ]] && ssh='[ssh] '
        printf "\033]0;%s%s@%s:%s\007" "$ssh" "$user" "$host" "$pwd"
}
PROMPT_COMMAND=_prompt_command

PROMPT_DIRTRIM=6

# load completion
. /etc/bash/bash_completion 2>/dev/null ||
        . ~/.bash_completion 2>/dev/null


eval "$(zoxide init --cmd cd bash)"
