#!/usr/bin/env bash

export EDITOR=nvim
export GREP_COLOR='1;36'
export PAGER='less'

# History
HISTFILE="$HOME/.bash_history"
HISTSIZE=10000000
HISTFILESIZE=10000000

# Aliases
alias v=nvim
alias lg=lazygit
alias ..='echo "cd .."; cd ..'

# Prompt command
_prompt_command() {
  # Sync history across all bash sessions
  history -a # Append new commands to history file
  history -c # Clear in-memory history
  history -r # Re-read history file
}

PROMPT_COMMAND=_prompt_command

PROMPT_DIRTRIM=6

eval "$(starship init bash)"

# load completion
. /etc/bash/bash_completion 2>/dev/null ||
  . ~/.bash_completion 2>/dev/null

eval "$(zoxide init --cmd cd bash)"
