#!/usr/bin/env bash

set -euo pipefail
shopt -s globstar

# Colors for output
RED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Change to the root of the repo.
cd "$(git rev-parse --show-toplevel)"

help() {
    echo "Usage: $0 [target]

To deploy a NixOS/darwin host:

    $0 clark

Options:

    --dry-run: build, but do not apply the changes
    --use-substitutes: instruct remote to download from cache.nixos.org if possible
    --build-remote: build on remote machine rather than locally
" >/dev/stderr
}

TARGETS=()
DRY_RUN=0
BUILD_REMOTE=0
EXTRA_SWITCH_ARGS=()
for i in "$@"; do
    case $i in
        --dry-run)
            DRY_RUN=1
            ;;
        --use-substitutes)
            EXTRA_SWITCH_ARGS+=("--use-substitutes")
            ;;
        --build-remote)
            BUILD_REMOTE=1
            ;;
        --help | -h)
            help
            exit 0
            ;;
        --* | -*)
            echo "Unknown option $i" >/dev/stderr
            echo "" >/dev/stderr
            exit 1
            ;;
        *)
            TARGETS+=("$i")
            ;;
    esac
done

if [ "${#TARGETS[@]}" -eq 1 ]; then
    TARGET=${TARGETS[0]}
else
    echo -e "${YELLOW}You must specify exactly one target${NC}" >/dev/stderr
    echo "" >/dev/stderr
    help
    exit 1
fi

function get_host_type(){
    local host="$1"

    # Determine system type
    if nix eval .#darwinConfigurations."${host}" --apply 'x: true' 2>/dev/null >/dev/null; then
        echo "darwin"
    elif nix eval .#nixosConfigurations."${host}" --apply 'x: true' 2>/dev/null >/dev/null; then
        echo "nixos"
    else
        echo -e "${RED}Error: Configuration doesn't exists!!${NC}" >/dev/stderr
        exit 1
    fi
}

function deploy_nixos() {
    local target="$1"
    shift

    local is_local=0
    if [ "$target" = "$(hostname)" ]; then
        is_local=1
    fi

    if [ $DRY_RUN == 1 ]; then
        echo -e "${GREEN}Building (but not deploying!) new system...${NC}"
        new_system=$(nix build ".#nixosConfigurations.$target.config.system.build.toplevel" --print-out-paths --no-link)
        if [ $is_local == 1 ]; then
            current_system=/run/current-system
        else
            current_system=$(ssh "$target" realpath /run/current-system)
            nix copy --from "ssh://$target" "$current_system"
        fi
        nix store diff-closures "$current_system" "$new_system"
        exit 0
    fi

    if [ "$target" = "$(hostname)" ]; then
        echo e "${BLUE}nixos-rebuild switch --use-remote-sudo --flake .#$target ${NC}"
        nixos-rebuild switch --use-remote-sudo --flake ".#$target"
    else
        echo -e "${BLUE}nixos-rebuild switch --use-remote-sudo --flake .#$target --target-host $target ${EXTRA_SWITCH_ARGS[*]} ${NC}"
        nixos-rebuild switch --use-remote-sudo --flake ".#$target" --target-host "$target" "${EXTRA_SWITCH_ARGS[@]}"
    fi
}

function deploy_darwin() {
    local target="$1"
    shift

    local is_local=0
    if [ "$target" = "$(hostname)" ]; then
        is_local=1
    fi

    if [ $DRY_RUN == 1 ]; then
        echo -e "${GREEN}Building (but not deploying!) new system...${NC}"
        new_system=$(nix build ".#darwinConfigurations.$target.config.system.build.toplevel" --print-out-paths --no-link)
        if [ $is_local == 1 ]; then
            current_system=/run/current-system
        else
            current_system=$(ssh "$target" realpath /run/current-system)
            nix copy --from "ssh://$target" "$current_system"
        fi
        nix store diff-closures "$current_system" "$new_system"
        exit 0
    fi

    echo -e "${BLUE}sudo darwin-rebuild switch --flake .#$target ${NC}"
    sudo darwin-rebuild switch --flake ".#$target"
}


SYSTEM_TYPE=$(get_host_type "$TARGET")

if [ "$SYSTEM_TYPE" = "darwin" ]; then
    if [ $BUILD_REMOTE == 1 ]; then
        echo -e "${YELLOW}Warning: --build-remote not supported for Darwin deployments${NC}" >/dev/stderr
    fi
    deploy_darwin "$TARGET"
else
    if [ $BUILD_REMOTE == 1 ]; then
        EXTRA_SWITCH_ARGS+=("--build-host" "$TARGET" "--fast")
    fi
    deploy_nixos "$TARGET"
fi
