name: "CI"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
 build:
   strategy:
     matrix:
       labels: [macOS, Linux]
     fail-fast: false

   runs-on: ${{matrix.labels}}
   steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.nixos.org/
      - uses: cachix/cachix-action@v12
        with:
          name: sinrohit
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run CI (Nix) 🔧
        run: nix run github:Mic92/nix-fast-build -- --no-nom
