name: "CI"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
 build:
   strategy:
     matrix:
       labels: [macOS, Linux]
     fail-fast: false

   runs-on: ${{matrix.labels}}
   steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v12
        with:
          name: sinrohit
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run CI (Nix) 🔧
        run: nixci build
